# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82eb9eea01caa68d1f42beace2ceb7f16d6418e5a099913f83fc5974af7f50e6f6eac654c0de2a12b81cb5324ce5b50b455e134710c65e54e6464568f07a4a33

test:
  secret_key_base: 37ef082024f7fd13383195c92261bb259b56b13b169c7e78587892ff8139ca36300b863a1e0f8e652c420c1124e884af7c05e292706e08cdad408053b2b88a2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
